### ISSUE TITLE
Only works on the last window

### ISSUE THREAD

**Issue by isaac-s** [lbarchive/KLTT#5]
The calculation of the number of open tabs should be based on the number of tabs in the current window. Currently, the extension will close all tabs in a window if there's another window open.

**Comment by livibetter** [comment]
I agree that there might be a need for different calculation, I didn't think about windows, but decided to count all tabs across all windows when I designed it.

Since, unfortunately, I am currently not a Chrome/Chromium user, so if anyone wants to contribute by adding a new option for this type of calculation, please open a pull request.

I rather not to code on this extension anymore, unless there is a significant amount of requests on an issue. Sorry, but you have to wait or to contribute.
